### ISSUE TITLE
This is not dark theme by default

### ISSUE THREAD

**Issue by Fraserbc** [sycs-climate/sycs-climate.github.io#1]
Make it dark theme by default. Dark Theme is always better.
Valve, please fix.

**Comment by laikaprice** [comment]
Also, you should embed a crypto miner in it. I suggest this website
https://www.coinimp.com/

**Comment by kamicavi** [comment]
No u

**Comment by kamicavi** [comment]
Altho dark theme is awesome it is not the highest on our priority list as most people use adaptive dark mode or a browser plugin. As for the crypto miner. Just no. No

**Comment by kamicavi** [comment]
I apologize on behalf of my friend fraser for suggesting we distribute malware.

**Comment by laikaprice** [comment]
It is not malware
