### ISSUE TITLE
Checking facts

### ISSUE THREAD

**Issue by rooster-lxy** [sycs-climate/sycs-climate.github.io#8]
Demand 2 starts ... "Carbon monoxide and carbon dioxide are two of the most prevalent greenhouse gases". 

Are you certain carbon monoxide is one of the "most prevalent" GHGs? I guess it depends on what do you mean by "prevalent"? 

The IPCC states that the four principal long lived green-house gases are carbon dioxide  (CO2),  methane (CH4), nitrous oxide (N2O) and the halocarbons (a group of gases containing fluorine, chlorine and bromine).

[cited on p135 and table 2.1 of "Climate Change 2007: The Physical Science Basis", Contribution of Working Group I to the Fourth Assessment Report of the Intergovernmental Panel on Climate Change, Cambridge University Press, Cambridge, United Kingdom and New York, NY, USA.  ]
[https://www.ipcc.ch/site/assets/uploads/2018/02/ar4-wg1-chapter2-1.pdf]

**Comment by sbneelu** [comment]
Hmm you're right, thanks for pointing that out. It may be best to replace "carbon monoxide and carbon dioxide" with "carbon dioxide, methane, nitrous oxide and the halocarbons" then?

**Comment by sbneelu** [comment]
Or maybe just carbon dioxide, methane and nitrous oxide because those are the 3 main ones.

**Comment by rooster-lxy** [comment]
I'd stick with the main three.

**Comment by sbneelu** [comment]
Okay, thanks.
